### PR TITLE
Update analyzer constraint

### PR DESCRIPTION
**Pull request by Attempt3035**
## Motivation
  I noticed analyzer was being resolved to a lower version than available, it's causing warnings in the build runner for freezed.

## Changes
  I opened the depended-on analyzer versions to include the 6.#.# major release, but less than 7.#.# (Not out yet anyway)

## Testing/QA Instructions
  I have no idea the implications this may have, and have not looked around this code base. From my testing, everything is operating normally as far as I can see, but this would need a maintainer to run some tests to confirm. I checked the changes in the analyzer package version notes, they seem minimal and I'm guessing won't affect anything with this package :)

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by Ghabs95 — APPROVED** [review]

**Review by matthewnitschke-wk — APPROVED** [review]

**Comment by matthewnitschke-wk** [comment]
@Attempt3035 Approach seems fine, looking at the changlog for v6 there's nothing that should effect dependency_validator, and we should catch any issues from the existing unit tests within the repo (we run on both dart 2 and 3)

CI failures are unrelated to this change, and were fixed here: https://github.com/Workiva/dependency_validator/pull/120, If you just merge master on this pr, we can re-run CI and get this merged! Thanks for putting the PR up!

**Comment by matthewnitschke-wk** [comment]
QA +1

- [x] CI passes is sufficient

🚀 @Workiva/release-management-p 🚢

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
