### PR TITLE
Update references to the previous team name

### PR DESCRIPTION
**Pull request by sourcegraph-wk**
This batch changes references to the former team name Client Platform to now reference Frontend Frameworks Architecture.

`replace "Client Platform" "Frontend Frameworks Architecture"`

### QA steps:

CI passing should be sufficient as these changes are documentation changes.

[_Created by Sourcegraph batch change `Workiva/Update_PR_Template_Team_Names_FEA`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/Update_PR_Template_Team_Names_FEA)

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by robbecker-wf — APPROVED** [review]

**Comment by robbecker-wf** [comment]
QA+1 CI passes

**Comment by robbecker-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
