### PR TITLE
UIP-3191 Dart 2.0 and DDC compatibility changes

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Description

* Strong-mode
* All recommended lints and fixes
* Increased ranges on `args`, `coverage`, and `dartdoc` to include versions that are also Dart 2.0 and DDC compatible.

## Testing
- [ ] CI passes (updated Travis CI config to run on stable and dev channels)

## Code Review
@Workiva/app-frameworks

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Module Findings
No security relevant content detected. Please review for security relevance and request security review as needed.

**Comment by robbecker-wf** [comment]
+1 thanks for using abide!

**Comment by robbecker-wf** [comment]
+10 CI passes. Ran locally with Dart 1 and Dart 2 without issue.

**Comment by robbecker-wf** [comment]
Quality Review Approval: +1 ( aka QA: +1 )

- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [x] Unit test created/updated
- [x] All unit tests pass
- [x] Rosie has run and reports properly the release the ticket will be included in

Merging into master.
@Workiva/release-management-p for merge into master

**Pull request merged**
