### PR TITLE
update build

### PR DESCRIPTION
**Pull request by josephswanson-wf**
- no need to use 6gb image for a pub get

Testing
- CI passes
- basic functionality

@jayudey-wf @jeffhall-wk @bradbenjamin-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by jeffhall-wk** [comment]
+1

**Comment by josephswanson-wf** [comment]
+1 good catch Jay

**Comment by jayudey-wf** [comment]
@Workiva/release-management-pp

**Pull request merged**
